# HPack configuration file
# Run hpack to generate corresponding .cabal file.
name: monad-lgbt
version: 0.0.1
author: Michal J. Gajda <mjgajda@gmail.com>
maintainer: Michal J. Gajda <mjgajda@gmail.com>
synopsis:  Monad transformers for combining local and global state.

description: >
      This is library providing a nice typeclass interface for monads
      with two different states: local and global.
      Local state is backtraced whenever intervening monad transformer backtracks.
      Global state is preserved across all backtracing.
      It provides nice, classy interface for monads
      with backtracking/backjumping/continuations.

category: Control
stability: beta
github:        
license: BSD2
github: mgajda/monad-lgbt

source-dirs:
        - src

library:
        exposed-modules:
                - Control.Monad.State.LGBT
                - Control.Monad.Backtrack

tests:
        spec:
                source-dirs:
                        - test
                main: Main.hs

dependencies:
        - logict
        # Unit testing
        - hspec
        - QuickCheck
        # benchmarking
        - deepseq
        # Generic libraries
        - base >=4.3 && <4.10
        - containers
        - mtl

